# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'JLPopAlertDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'
  pod 'YYText', '~> 1.0.7'
  # Pods for JLPopAlertDemo

end
